### ISSUE TITLE
Передача стейта в функцию 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#11]
```
this.onSortCarItems(this.state);
```
Передавай в функции только что её действительно нужно. Передавать все подряд плохая практика. Подобная передача параметров - неявная, и сложно сказать что там было передано на самом деле

Если тебе нужен стейт в функции. То лучше получить значения стейта внутри функции

**Comment by bambuuk** [comment]
Поправил данную ошибку (передал в функцию нужные ел стейта, а не весь стейт)
