### ISSUE TITLE
Немного по структуре

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#12]
Называй папки внутри папки `components` с большой буквы. Так просто принято)

`App.js` можешь вернуть обратно в `src`, обычно его никто никуда не переносит

**Comment by DmitriiMelnikOnix** [comment]
перенеси папку `pages` в `src`

**Comment by bambuuk** [comment]
Переименовал все папки с большой букви каталога components. App.js перенёс в папку src.
