### ISSUE TITLE
AddCars.js includes

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#13]
```
if (this.state.typeCar === 'Седан' || this.state.typeCar === 'Пикап' || this.state.typeCar === 'Универсал') {
```
Я как-то писал об этом. Смотри как можно переделать эту строку

```
const {typeCar} = this.state;
const typeCarList = ['Седан', 'Пикап', 'Универсал']; // это лучше вынести вообще отдельно в константы
if (typeCarList.includes(typeCar)) {
...
```

Дело в том что если везде прописывать вариант выбора как строки, то можно легко сделать ошибку в написании или например обновлять все подобные условия, если у тебя появятся в продаже допусти кроссоверы) 
В во втором случае нужно будет лишь добавить кроссовер в массив, который может использоваться во многих местах

В идеале у тебя 'Седан', 'Пикап', 'Универсал' как строка должны быть записаны лишь один раз в константах

**Comment by bambuuk** [comment]
Да, ранее эта ошибка была вынесена в задаче 4. Но что-то у меня тогда не пошле с её исправлением. 
https://github.com/bambuuk/uber-adaptiv-and-js/issues/4

Ошибку поправил (условие переделал)
