### ISSUE TITLE
AddCars.js копирование обьекта

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#17]
```
const copyState = Object.assign({}, this.state);
const { title, typeCar, classComfort, driver, url } = copyState;
```
В данном случае копирование обьекта бессмысленно, так как ты его никак не изменяется. Так что можно удалить строку с копированием

**Comment by DmitriiMelnikOnix** [comment]
Подобное и в `ChoiseCar.js` 
```
const copyData = [...this.state.data];
const count = this.state.countClickArrow;
const id = copyData[count];
```
Если не изменяешь массив то нет смыла его копировать

**Comment by bambuuk** [comment]
Убрал выше указанные копии стейтов
