### ISSUE TITLE
onActiveCard тоже можно упростить условие

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#18]
```
const activeItemInArr = copyData.map(item => item.id === id ? { ...item, active: !item.active } : item)
```
Во многих случаях можно использовать тернарный оператор

**Comment by bambuuk** [comment]
Поправил код
Вместо условий использовал тернарный оператор в переменной activeItemInArr метода onActiveCard.
