### ISSUE TITLE
Предупреждение в консоли браузера

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#2]
Ты удалил картинку, но это картинка используется в `public/manifest.json`. Желательно чтобы консоль всегда была чистой. Можешь удалить эту картинку и из `manifest.json`
<img width="1011" alt="Снимок экрана 2022-05-07 в 18 13 13" src="https://user-images.githubusercontent.com/59687966/167260391-c962e7c7-dd41-4273-8bd7-ce48c8d9c7f7.png">

**Comment by bambuuk** [comment]
Удалил manifest.json и link на него в index.html
