### ISSUE TITLE
MainPage.js и Frame 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#27]
В `MainPage.js` пустые скобки выглядят не очень и от них легко избавиться заменит в `Layout`
```
children: PropTypes.element.isRequired
```
на 
```
children: PropTypes.node.isRequired
```

PropTypes.node - это по сути любые данные которые могут быть переданы в children. То есть строка, элемент или массив элементов

**Comment by bambuuk** [comment]
Поправил данную ошибку - убрал фрагмент в MainPage.js и в Layout.js поправил в proptypes - children: PropTypes.node.isRequired
