### ISSUE TITLE
 PropTypes.instanceOf(Object),

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#28]
`PropTypes.instanceOf(Object),` я так понимаю это способ обойти правила eslint. Если данные из обьекта у тебя в этом компоненте не используются то так можно, но лучше записать вот так `PropTypes.shape({})`
Но если как в `AddCarsView.js` ты используешь данные из компонента. То нужно всех их перечислить
 ```
 PropTypes.shape({
  title: PropTypes.string, 
  typeCar: PropTypes.string, 
  classComfort: PropTypes.string, 
  driver: PropTypes.string, 
  url: PropTypes.string,
})
 ```

**Comment by DmitriiMelnikOnix** [comment]
А в `CarList.js` можешь описать `data` как `PropTypes.arrayOf(PropTypes.share({}))`

**Comment by bambuuk** [comment]
Поправил данные ошибки в указанных компонентах и также пересмотрел и поправил в других компонентах, где это было необходимо
