### ISSUE TITLE
Reasons.js useState

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#29]
```
 const [reasonsList, setReasonsList] = useState([
 ```

если ты не используешь `setReasonsList` вместо того чтобы отключать правила, можно просто удалить `setReasonsList`

```
 const [reasonsList] = useState([
 ```

**Comment by bambuuk** [comment]
Удалил метод cardsList и убрал отключения правила в компоненте Reasons.
