### ISSUE TITLE
Передача обьекта и его изменение

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#3]
Специально перепроверил будет ли какая-то проблема с этим, так как бы не до конца уверен

```
this.props.onAddItem(this.state);
this.setState({
    title: '',
    typeCar: '',
    classComfort: '',
    driver: '',
    url: ''
})
```

Смотри что происходит, ты передаешь весь стейт в качестве параметра в функцию, но стейт это обьект и если его мутировать то он измениться во всех местах. 

В данном случаи у тебя все работает нормально, но только из-за того что не успевает сломаться)
Как оказалось функция setState не создает новый обьект, а мутирует его, и если бы у тебя был бы какой-то запрос на бекенд который использовал эти данные, то данные каждый раз были пустыми

Вот пример как я проверял, если интересно
```
 sendCarItem = (e) => {
        e.preventDefault();
        if (this.state.typeCar === 'Седан' || this.state.typeCar === 'Пикап' || this.state.typeCar === 'Универсал') {
            this.props.onAddItem(this.state);
            this.setState({
                title: '',
                typeCar: '',
                classComfort: '',
                driver: '',
                url: ''
            }, () => console.log('test', this.state))
        } else {
            alert('Тип автомобиля может быть: Седан, Пикап, Универсал. Пожалуйста, впишите один из предложенных вариантов')
        }
    }
```
Я добавил второй параметр для `setState`, это функция которая отработает после изменения стейта. В ней вывел в консоль текущий стейт. Если бы там вывелось данные которые были введены пользователем - значит все хорошо, и проблем бы не было, но там вывелся обьект с пустыми строками

Ух, много текста, а теперь суть, передавать нужные поля отдельно)

**Comment by bambuuk** [comment]
Поправил данную ошибку. путём передачи копии стейта и розделил передачу на отдельные елементы.
