### ISSUE TITLE
Сохранение функции в стейте

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#31]
```
const [state, setState] = useState({
  theme: 'light', // eslint-disable-line
  choiseTheme: choiseTheme, // eslint-disable-line
});

function choiseTheme(propsTheme) {
  setState({
    ...state,
    theme: propsTheme
  }); // eslint-disable-line
}
```

1. Думаю можно обойтись без отключений правил eslint
2. Сохранять функцию в стейте это плохая идея так как внешние переменные не будут в ней изменяться. Используй `useMemo` чтобы передать обьект в контекст (кажется я тебе уже писал об этом, если нет пиши - подскажу если нужно будет)

**Comment by bambuuk** [comment]
Переделал передачу объекта с данными в контекст - изменил стейт - убрал функцию изминения стейт и сделал сам стейт в обычном формате. Сделал передачу объекта с theme и ф-цией е' изменения в контекст, с помощью useMemo
