### ISSUE TITLE
сохранение языка при перезагрузке страницы

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#32]
если удалить в `i18n/index.js` строку `lng: 'ua',`
то язык будет сохраняться после перезагрузке страницы

Во всяком случае у меня начало сохранятся :)

**Comment by bambuuk** [comment]
Исправил данную проблему путём передачи текущего языка из localStorage в кнопку выбора языка и убрал настройку lng из настройки i18next
