### ISSUE TITLE
Значение языка из localStorage

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#33]
`<select name="language" value={localStorage.getItem('i18nextLng')} onChange={onChangeLanguage}>`

лучше получать значение языка из i18n.language а не из localStorage, так будет надежнее

**Comment by bambuuk** [comment]
Заменил в кнопке выбора языка значение получения value на  i18n.language вместо localStorage.getItem('i18nextLng').
