### ISSUE TITLE
константы для dark и light

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#34]
так как ты часто пишешь строки `dark` и `light` и чтобы где-то случайно не ошибиться лучше создать константы в которых будут эти строки, а там где нужно их можно импортировать

**Comment by bambuuk** [comment]
Положил цвета для изменения тем по переменным и использовал их в нужных местам. Также добавил константы для выбора тем в HeaderView
