### ISSUE TITLE
Сравнение с вводными данными

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#4]
```
this.state.typeCar === 'Седан' || this.state.typeCar === 'Пикап' || this.state.typeCar === 'Универсал'
```
Всегда нужно думать что пользователь введет с маленькой буквы, с большой буквой в середине и с пробелом в начале и в конце, вот так это будет уже интересно)

**Comment by DmitriiMelnikOnix** [comment]
Так же возможно тебе понадобится функция `includes` чтобы это условие стало меньше

**Comment by bambuuk** [comment]
"this.state.typeCar === 'Седан' || this.state.typeCar === 'Пикап' || this.state.typeCar === 'Универсал'
Всегда нужно думать что пользователь введет с маленькой буквы, с большой буквой в середине и с пробелом в начале и в конце, вот так это будет уже интересно)" 

- исправил данную ошибку путём замены input на выпадающий список (тег select) [link](https://prnt.sc/A0U_mGrPAA_L)
