### ISSUE TITLE
map

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [bambuuk/uber-adaptiv-and-js#6]
```
const arr = [];
data.forEach(item => {
    arr.push(item.title);
})
```
Именно это должен делать `map`

**Comment by DmitriiMelnikOnix** [comment]
```
const res = [];
arrSort.forEach(arrSortItem => {
    data.forEach(dataItem => {
        if (dataItem.title === arrSortItem) {
            res.push(dataItem);
        }
    })
})
```
Думаю этот код тоже можно переписать с использованием `map`

**Comment by DmitriiMelnikOnix** [comment]
Хотя, погоди
Кажется можно вообще убрать весь этот код если добавить функцию для sort
```
const arrSort = arr.sort((item1, item2) => item1.title > item2.title ? 1: -1);
```

**Comment by bambuuk** [comment]
Участок [кода1](https://prnt.sc/wh4xPd83jaIu) больше не понадобился, так как вместо такого [варианта](https://prnt.sc/-_1-WWikOn52) сортировки массива с объектами по title, использовал вот такой вариант:

const res = data.sort((item1, item2) => item1.title > item2.title ? 1 : -1);
